ssh-dev-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem

ssh-prod-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem
ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@15.237.160.222

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@51.44.171.48

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@15.236.42.164

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@35.180.23.61

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@15.237.101.133

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@15.237.186.87

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@35.181.171.1

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@35.180.24.237

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@52.47.80.107

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@51.44.170.219

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@13.38.15.131

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@13.37.223.219

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@13.36.165.141

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@15.237.189.68

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@35.180.250.7

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@35.181.7.247

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@35.181.168.230

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@3.67.89.17

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@18.199.240.57

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@18.198.209.163

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@13.38.55.122

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@51.45.3.44

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@52.47.87.25

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@13.38.10.59

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@3.76.31.151

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@3.69.168.113

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@54.93.218.175

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@54.93.185.0

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@18.197.145.185

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@13.38.61.39

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@63.179.249.166

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@35.180.29.251

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@13.37.216.79

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@35.180.31.198

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@3.120.16.1

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@18.184.193.47

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@51.44.5.218

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@15.188.64.106

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@3.70.217.34

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@18.195.103.59

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@13.38.219.58

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@35.180.186.112

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@3.121.42.49

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@63.179.100.56

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@13.39.156.115

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@3.120.205.140

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@13.36.208.143

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@13.37.107.173

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@3.72.255.22

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@13.38.228.245

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@63.181.0.174

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@35.181.155.107

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@35.159.112.167

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@18.197.155.166

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@35.180.42.47

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@13.39.109.144

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@18.185.77.139

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@35.180.174.236

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@35.181.50.200

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@18.197.26.200

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@52.57.47.118

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@13.39.156.172

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@35.180.227.127

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@35.181.151.64

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@3.124.242.181

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@35.180.156.170

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@13.38.130.114

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@35.180.186.147

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@18.196.103.74

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@54.93.252.179

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@13.39.50.54

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@3.124.192.12

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@35.181.169.97

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@15.237.178.217

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@15.237.174.177

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@15.188.147.69

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@35.180.232.225

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@13.36.177.246

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@51.44.162.77

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@51.44.182.4

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@13.37.188.201

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@51.44.111.108

ssh-dev-france-backend-instance:
	ssh -i ./keys/dev-france-backend-instance-key.pem admin@13.39.56.35

ssh-dev-france-frontend-instance:
	ssh -i ./keys/dev-france-frontend-instance-key.pem admin@52.47.213.255

ssh-prod-france-backend-instance:
	ssh -i ./keys/prod-france-backend-instance-key.pem admin@35.180.92.58

ssh-prod-france-backend-instance:
	ssh -i ./keys/prod-france-backend-instance-key.pem admin@35.180.92.58

ssh-prod-france-backend-instance:
	ssh -i ./keys/prod-france-backend-instance-key.pem admin@35.180.92.58

ssh-prod-france-frontend-instance:
	ssh -i ./keys/prod-france-frontend-instance-key.pem admin@13.38.118.195

ssh-prod-france-backend-instance:
	ssh -i ./keys/prod-france-backend-instance-key.pem admin@15.236.73.143

ssh-prod-france-frontend-instance:
	ssh -i ./keys/prod-france-frontend-instance-key.pem admin@15.188.220.31

