ssh-dev-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem

ssh-prod-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem
ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@15.237.160.222

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@51.44.171.48

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@15.236.42.164

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@35.180.23.61

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@15.237.101.133

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@15.237.186.87

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@35.181.171.1

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@35.180.24.237

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@52.47.80.107

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@51.44.170.219

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@13.38.15.131

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@13.37.223.219

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@13.36.165.141

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@15.237.189.68

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@35.180.250.7

ssh-dev-france-instance:
	ssh -i ./keys/dev-france-instance-key.pem admin@35.181.7.247

ssh-prod-france-instance:
	ssh -i ./keys/prod-france-instance-key.pem admin@35.181.168.230

ssh-staging-germany-instance:
	ssh -i ./keys/staging-germany-instance-key.pem admin@3.67.89.17

ssh-dev-germany-instance:
	ssh -i ./keys/dev-germany-instance-key.pem admin@18.199.240.57

ssh-prod-germany-instance:
	ssh -i ./keys/prod-germany-instance-key.pem admin@18.198.209.163

ssh-staging-france-instance:
	ssh -i ./keys/staging-france-instance-key.pem admin@13.38.55.122

